
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: metrics
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
    - grafana-data:/var/lib/grafana

  fastapi:
    build: ./python-app
    container_name: producer
    command: uvicorn producer:app --host 0.0.0.0 --port 8000
    depends_on: 
      - kafka
    # Inicia el contenedor despues de que inicie el de Kafka. Sin embargo, el SERVICIO de Kafka puede 
    # tardar un poco mas en estar listo para aceptar conexiones, porque lo que se agrego un retardo en el codigo de la
    # aplicacion.
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  consumer:
    build: ./python-app
    container_name: consumer
    command: python consumer.py
    depends_on:
      - kafka
      - influxdb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_DB: metrics

volumes: # Se definen volúmenes para persistencia de datos
  influxdb-data:
  grafana-data:

